namespace: mgmt

secret:
  name: github-tokens
  tokens:
    bjoernPetersen: __GITHUB_TOKEN_BJOERNPETERSEN__
    openAlcoholics: __GITHUB_TOKEN_OPENALCOHOLICS__
    torbenCarstens: __GITHUB_TOKEN_TORBENCARSTENS__
    preparingForExams: __GITHUB_TOKEN_PREPARINGFOREXAMS__
    timHatDieHandAnDerMaus: __GITHUB_TOKEN_TIMHATDIEHANDANDERMAUS__
    woogLife: __GITHUB_TOKEN_WOOGLIFE__

cronjob:
  name: renew-kubeconfig-github-secrets
  image: ghcr.io/openalcoholics/github-kubeconfig-renewal:__TAG__
  schedule: "*/15 * * * *"
  backoffLimit: 0
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  restartPolicy: Never
  labels:
    app: renew-kubeconfig-github-secrets
  requests:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 300m
    memory: 300Mi

rbac:
  clusterrole:
    name: read:serviceaccounts
  clusterrolebinding:
    name: read:serviceaccounts
  serviceaccount:
    name: github-kubeconfig-renewal
