apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- range $k, $v := .Values.cronjob.labels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        spec:
          serviceAccountName: {{ .Values.rbac.serviceaccount.name }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          containers:
            - name: {{ .Values.cronjob.name }}
              image: {{ .Values.cronjob.image }}
              env:
                - name: PYTHONUNBUFFERED
                  value: "1"
              envFrom:
                - secretRef:
                    name: {{ .Values.secret.name }}
              resources:
                requests:
                  cpu: {{ .Values.cronjob.requests.cpu }}
                  memory: {{ .Values.cronjob.requests.memory }}
                limits:
                  cpu: {{ .Values.cronjob.limit.cpu }}
                  memory: {{ .Values.cronjob.limit.memory }}
