apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
data:
  GITHUB_TOKEN_OPENALCOHOLICS: {{ .Values.secret.tokens.openAlcoholics }}
  GITHUB_TOKEN_TORBENCARSTENS: {{ .Values.secret.tokens.torbenCarstens }}
  GITHUB_TOKEN_PREPARINGFOREXAMS: {{ .Values.secret.tokens.preparingForExams }}
  GITHUB_TOKEN_TIMHATDIEHANDANDERMAUS: {{ .Values.secret.tokens.timHatDieHandAnDerMaus }}
  GITHUB_TOKEN_WOOGLIFE: {{ .Values.secret.tokens.woogLife }}
